#!/usr/bin/env python

"""
Plot synthetic data generated by recon3d.py

Usage:  plot_data.py prefix cols 

"""
import sys,os
import numpy as np
import matplotlib.cm as cm
import matplotlib.pyplot as plt


def main(args):
   prefix = args[0]
   while prefix[-1] == '.': prefix = prefix[:-1]
   cols = np.int32(args[1])

   east, north, up = read_data(prefix,cols)
   plot_data(east,north,up)


def plot_data(east,north,up):
   fig = plt.figure(figsize=(12,8))
   surf = plt.imshow(east,cmap=cm.seismic)
#   plt.clim([-10,10])
   cbar = fig.colorbar(surf)
   plt.title('East')

   fig = plt.figure(figsize=(12,8))
   surf = plt.imshow(north,cmap=cm.seismic)
#   plt.clim([-10,10])
   cbar = fig.colorbar(surf)
   plt.title('North')

   fig = plt.figure(figsize=(12,8))
   surf = plt.imshow(up,cmap=cm.hot)
#   plt.clim([-10,10])
   cbar = fig.colorbar(surf)
   plt.title('Up')

   plt.show() 

def read_data(prefix,cols):
   fid = open(prefix+'.east','r')
   east = np.fromfile(fid,dtype=np.float32)
   east = east.reshape(-1,cols)
   fid.close()

   fid = open(prefix+'.north','r')
   north = np.fromfile(fid,dtype=np.float32)
   north = north.reshape(-1,cols)
   fid.close()

   fid = open(prefix+'.up','r')
   up = np.fromfile(fid,dtype=np.float32)
   up = up.reshape(-1,cols)
   fid.close()

   return east, north, up

if __name__ == '__main__':
   args = sys.argv[1:]
   if len(args) != 2:
      print __doc__
      sys.exit()
   main(args)
